//! Adaptação Rust segura do gerador Grisu2 de `redis/8.10.1/deps/fpconv`.
//! Mantém a seleção de potências e o arredondamento da referência.
//!
//! Copyright (c) 2021, Redis Labs
//! Copyright (c) 2013-2019, night-shift <as.smljk at gmail dot com>
//! Copyright (c) 2009, Florian Loitsch <florian.loitsch at inria dot fr>
//! All rights reserved.
//!
//! Boost Software License - Version 1.0 - August 17th, 2003
//!
//! Permission is hereby granted, free of charge, to any person or organization
//! obtaining a copy of the software and accompanying documentation covered by
//! this license (the "Software") to use, reproduce, display, distribute,
//! execute, and transmit the Software, and to prepare derivative works of the
//! Software, and to permit third-parties to whom the Software is furnished to
//! do so, all subject to the following:
//!
//! The copyright notices in the Software and this entire statement, including
//! the above license grant, this restriction and the following disclaimer,
//! must be included in all copies of the Software, in whole or in part, and
//! all derivative works of the Software, unless such copies or derivative
//! works are solely in the form of machine-executable object code generated by
//! a source language processor.
//!
//! THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//! IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//! FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
//! SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
//! FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
//! ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//! DEALINGS IN THE SOFTWARE.

#[derive(Clone, Copy)]
struct Fp {
    fraction: u64,
    exponent: i32,
}

impl Fp {
    fn normalize(self) -> Self {
        let shift = self.fraction.leading_zeros();
        Self {
            fraction: self.fraction << shift,
            exponent: self.exponent - shift as i32,
        }
    }
    fn multiply(self, other: Self) -> Self {
        let product = u128::from(self.fraction) * u128::from(other.fraction);
        Self {
            fraction: ((product + (1u128 << 63)) >> 64) as u64,
            exponent: self.exponent + other.exponent + 64,
        }
    }
}

fn round(digits: &mut [u8], delta: u64, mut remainder: u64, unit: u64, distance: u64) {
    while remainder < distance
        && delta - remainder >= unit
        && (remainder + unit < distance || distance - remainder > remainder + unit - distance)
    {
        *digits.last_mut().expect("ao menos um dígito") -= 1;
        remainder += unit;
    }
}

/// Dígitos significativos e potência de dez para um número positivo e finito.
pub(super) fn digits(value: f64) -> (String, i32) {
    debug_assert!(value > 0.0 && value.is_finite());
    let bits = value.to_bits();
    let encoded_exponent = ((bits >> 52) & 0x7ff) as i32;
    let hidden = 1u64 << 52;
    let w = Fp {
        fraction: (bits & (hidden - 1)) | if encoded_exponent != 0 { hidden } else { 0 },
        exponent: if encoded_exponent != 0 {
            encoded_exponent - 1075
        } else {
            -1074
        },
    };
    let upper = Fp {
        fraction: (w.fraction << 1) + 1,
        exponent: w.exponent - 1,
    }
    .normalize();
    let shift = if w.fraction == hidden { 2 } else { 1 };
    let lower = Fp {
        fraction: ((w.fraction << shift) - 1) << (w.exponent - shift - upper.exponent),
        exponent: upper.exponent,
    };
    let approximation = (-(upper.exponent + 87) as f64 * 0.301_029_995_663_981_14) as i32;
    let mut index = ((approximation + 348) / 8) as usize;
    loop {
        let exponent = upper.exponent + POWERS[index].1 + 64;
        if exponent < -60 {
            index += 1;
        } else if exponent > -32 {
            index -= 1;
        } else {
            break;
        }
    }
    let power = Fp {
        fraction: POWERS[index].0,
        exponent: POWERS[index].1,
    };
    let w = w.normalize().multiply(power);
    let mut upper = upper.multiply(power);
    let mut lower = lower.multiply(power);
    upper.fraction -= 1;
    lower.fraction += 1;
    let mut decimal_power = 348 - index as i32 * 8;
    let distance = upper.fraction - w.fraction;
    let mut delta = upper.fraction - lower.fraction;
    let shift = (-upper.exponent) as u32;
    let one = 1u64 << shift;
    let mut integer = upper.fraction >> shift;
    let mut fractional = upper.fraction & (one - 1);
    let mut digits = Vec::with_capacity(18);
    let mut remaining = 10;
    let mut divisor = 1_000_000_000u64;
    while remaining > 0 {
        let digit = integer / divisor;
        if digit != 0 || !digits.is_empty() {
            digits.push(b'0' + digit as u8);
        }
        integer %= divisor;
        remaining -= 1;
        let remainder = (integer << shift) + fractional;
        if remainder <= delta {
            decimal_power += remaining;
            round(&mut digits, delta, remainder, divisor << shift, distance);
            return (
                String::from_utf8(digits).expect("dígitos ASCII"),
                decimal_power,
            );
        }
        divisor /= 10;
    }
    let mut unit = 10u64;
    loop {
        fractional *= 10;
        delta *= 10;
        remaining -= 1;
        let digit = fractional >> shift;
        if digit != 0 || !digits.is_empty() {
            digits.push(b'0' + digit as u8);
        }
        fractional &= one - 1;
        if fractional < delta {
            decimal_power += remaining;
            round(&mut digits, delta, fractional, one, distance * unit);
            return (
                String::from_utf8(digits).expect("dígitos ASCII"),
                decimal_power,
            );
        }
        unit *= 10;
    }
}

const POWERS: [(u64, i32); 87] = [
    (18054884314459144840, -1220),
    (13451937075301367670, -1193),
    (10022474136428063862, -1166),
    (14934650266808366570, -1140),
    (11127181549972568877, -1113),
    (16580792590934885855, -1087),
    (12353653155963782858, -1060),
    (18408377700990114895, -1034),
    (13715310171984221708, -1007),
    (10218702384817765436, -980),
    (15227053142812498563, -954),
    (11345038669416679861, -927),
    (16905424996341287883, -901),
    (12595523146049147757, -874),
    (9384396036005875287, -847),
    (13983839803942852151, -821),
    (10418772551374772303, -794),
    (15525180923007089351, -768),
    (11567161174868858868, -741),
    (17236413322193710309, -715),
    (12842128665889583758, -688),
    (9568131466127621947, -661),
    (14257626930069360058, -635),
    (10622759856335341974, -608),
    (15829145694278690180, -582),
    (11793632577567316726, -555),
    (17573882009934360870, -529),
    (13093562431584567480, -502),
    (9755464219737475723, -475),
    (14536774485912137811, -449),
    (10830740992659433045, -422),
    (16139061738043178685, -396),
    (12024538023802026127, -369),
    (17917957937422433684, -343),
    (13349918974505688015, -316),
    (9946464728195732843, -289),
    (14821387422376473014, -263),
    (11042794154864902060, -236),
    (16455045573212060422, -210),
    (12259964326927110867, -183),
    (18268770466636286478, -157),
    (13611294676837538539, -130),
    (10141204801825835212, -103),
    (15111572745182864684, -77),
    (11258999068426240000, -50),
    (16777216000000000000, -24),
    (12500000000000000000, 3),
    (9313225746154785156, 30),
    (13877787807814456755, 56),
    (10339757656912845936, 83),
    (15407439555097886824, 109),
    (11479437019748901445, 136),
    (17105694144590052135, 162),
    (12744735289059618216, 189),
    (9495567745759798747, 216),
    (14149498560666738074, 242),
    (10542197943230523224, 269),
    (15709099088952724970, 295),
    (11704190886730495818, 322),
    (17440603504673385349, 348),
    (12994262207056124023, 375),
    (9681479787123295682, 402),
    (14426529090290212157, 428),
    (10748601772107342003, 455),
    (16016664761464807395, 481),
    (11933345169920330789, 508),
    (17782069995880619868, 534),
    (13248674568444952270, 561),
    (9871031767461413346, 588),
    (14708983551653345445, 614),
    (10959046745042015199, 641),
    (16330252207878254650, 667),
    (12166986024289022870, 694),
    (18130221999122236476, 720),
    (13508068024458167312, 747),
    (10064294952495520794, 774),
    (14996968138956309548, 800),
    (11173611982879273257, 827),
    (16649979327439178909, 853),
    (12405201291620119593, 880),
    (9242595204427927429, 907),
    (13772540099066387757, 933),
    (10261342003245940623, 960),
    (15290591125556738113, 986),
    (11392378155556871081, 1013),
    (16975966327722178521, 1039),
    (12648080533535911531, 1066),
];
