[package]
name = "sider-fuzz"
version = "0.0.0"
edition = "2024"
publish = false
license = "MIT"

[package.metadata]
cargo-fuzz = true

[dependencies]
bytes = "1"
libfuzzer-sys = "=0.4.13"
sider = { path = ".." }

[[bin]]
name = "resp_decoder"
path = "fuzz_targets/resp_decoder.rs"
test = false
doc = false
bench = false

[workspace]
members = ["."]
